Fix `notifylist` Acceptance Tests
The resource was not in sync with the API, specifically both `hipchat` & `user` configs were no longer accepted as per these error messages:
```
        Error: PUT https://api.nsone.net/v1/lists: 400 Input validation failed (Value u'hipchat' for field '<obj>.notify_list[0].type' is not in the enumeration: ['email', 'webhook', 'datafeed', 'slack', 'pagerduty'])
```
```
        Error: PUT https://api.nsone.net/v1/lists: 400 Input validation failed (Value u'user' for field '<obj>.notify_list[0].type' is not in the enumeration: ['email', 'webhook', 'datafeed', 'slack', 'pagerduty'])
```

Therefore, both `hipchat` & `user` config related code has been removed.